project:
  group: laplacian
  name: model.metamodel
  type: model
  namespace: laplacian
  version: '1.0.0'
  source_repository:
    url: https://github.com/nabla-squared/laplacian.model.metamodel.git
    branch: master
  subprojects: []
  schemas: []
  templates: []
  models: []
  model_files: []
  template_files: []
