project:
  group: laplacian
  name: metamodel
  type: domain-model
  namespace: laplacian.metamodel
  version: '1.0.0'
  description:
    en: |
      This model is a model for defining a model, i.e. a metamodel.
      In this model, you can define a model with the following structure

      - attribute
      - relationship
      - aggregation
      - inheritance
    ja: |
      このモデルはモデルを定義するためのモデル(=メタモデル)です。
      このモデルでは、以下の構造を持つモデルを定義することができます。

      - 属性
      - 関連
      - 集約
      - 継承
    zh: |
      这个模型是一个定义模型的模型。(= metamodel)
      在这个模型中，你可以定义一个模型，其结构如下

      - attribute
      - relationship
      - aggregation
      - inheritance
  source_repository:
    url: https://github.com/laplacian-core/metamodel.git
    branch: master
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  templates:
  - group: laplacian
    name: domain-model.project-template
    version: '1.0.0'
