package laplacian.metamodel
import com.github.jknack.handlebars.Context
import laplacian.gradle.task.generate.ExecutionContext
import laplacian.metamodel.gradle.MetamodelModelEntryResolver
import laplacian.metamodel.model.EntityList
import laplacian.metamodel.model.ValueDomainTypeList
import laplacian.util.*
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import java.io.File
import java.nio.file.FileSystems
import java.nio.file.Files
import java.nio.file.Paths
import java.util.stream.Collectors

/**
 * A test utility class to assert the content of files which are generated by the templates.
 */
class MetamodelTemplateAssertion {
    lateinit var context: ExecutionContext
    lateinit var entities: EntityList
    lateinit var valueDomainTypes: ValueDomainTypeList
    /**
     * Read the model object from the given yaml files.
     */
    fun withModel(files: List<File>): MetamodelTemplateAssertion {
        context = ExecutionContext().apply {
            modelFiles.addAll(files)
            modelEntryResolvers.add(MetamodelModelEntryResolver())
        }
        context.build()
        entities = context.currentModel.get("entities") as EntityList
        valueDomainTypes = context.currentModel.get("value_domain_types") as ValueDomainTypeList
        return this
    }
    /**
     * Read the model object from the given yaml files.
     */
    fun withModel(path: String, glob: String = "{*,**/*}.yml"): MetamodelTemplateAssertion {
        val m = FileSystems.getDefault().getPathMatcher("glob:$path/$glob")
        val files = Files.walk(Paths.get(path))
                   .filter { m.matches(it) }
                   .map{ it.toFile() }
                   .collect(Collectors.toList())
        withModel(files)
        return this
    }
    /**
     * Read the model object from the given yaml expression.
     */
    fun withModelText(text: String): MetamodelTemplateAssertion {
        val temp = File.createTempFile(MetamodelTemplateAssertion::javaClass.name, ".yml")
        temp.deleteOnExit()
        temp.writeText(text)
        withModel(listOf(temp))
        return this
    }
    lateinit var template: File
    /**
     * Set the test target template file.
     */
    fun withTemplate(templatePath: String): MetamodelTemplateAssertion {
        template = File(templatePath)
        return this
    }
    /**
     * Assert that the contents of the given file and generated one are same.
     */
    fun assertSameContent(toBeSourceCodePath: String, handleModel:MetamodelTemplateAssertion.() -> Map<String, Any?> = { emptyMap() }) {
        val child = handleModel.invoke(this)
        val ctx = Context.newContext(context.currentModel, child)
        val actual = template.readText().handlebars().apply(ctx)
        val expect = File(toBeSourceCodePath).readText()
        assertEquals(expect.stripDocComments(), actual.stripDocComments())
    }
    /**
     * Assert that the content of the generated file contains the given string.
     */
    fun assertContains(content: String, handleModel:MetamodelTemplateAssertion.() -> Map<String, Any?> = { emptyMap() }) {
        val child = handleModel.invoke(this)
        val ctx = Context.newContext(context.currentModel, child)
        val actual = template.readText().handlebars().apply(ctx).stripDocComments()
        val expect = content.stripDocComments()
        val result = actual.replace("""(\n|^)\s*""".toRegex(), "\n").contains(expect.replace("""(\n|^)\s*""".toRegex(), "\n"))
        assertTrue(result, "\n---\n$expect\n---\nThe above content should be included in the following generated code:\n---\n${actual}")
    }
}
