project:
  group: laplacian
  name: metamodel-plugin
  type: domain-model-plugin
  namespace: laplacian.metamodel
  version: '1.0.0'
  description:
    en: |
      A domain model plugin module for the metamodel.
    ja: |
      metamodel のドメインモデルプラグインモジュール
    zh: |
      metamodel 域模型插件模块
  module_repositories:
    local:
      ../../../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  models:
  - group: laplacian
    name: metamodel
    version: '1.0.0'
