project:
  sources:
  - "src/entities/value_domain_type.yml"
  - "src/entities/entity/example.yaml"
  - "src/entities/query.yml"
  - "src/entities/named_value.yml"
  - "src/entities/value_domain.yml"
  - "src/entities/named_param.yml"
  - "src/entities/property_mapping.yml"
  - "src/entities/relationship.yml"
  - "src/entities/property.yml"
  - "src/entities/entity.yml"
  - ".editorconfig"
  - ".gitignore"
  - "doc/image/model-diagram.svg"
  - "doc/entities/Entity.md"
  - "doc/entities/ValueDomainType.md"
  - "doc/entities/Property.md"
  - "doc/entities/NamedValue.md"
  - "doc/entities/ValueItem.md"
  - "doc/entities/ValueDomain.md"
  - "doc/entities/Relationship.md"
  - "doc/entities/PropertyMapping.md"
  - "doc/entities/NamedParam.md"
  - "doc/entities/Query.md"
  - "README.md"
  - ".gitattributes"
  - "model/project.yaml"
  - "model/project/sources.yaml"
