project:
  sources:
  - "model/project/sources.yaml"
  - "model/project.yaml"
  - "src/entities/entity/example.yaml"
  - "src/entities/entity.yml"
  - "src/entities/property_mapping.yml"
  - "src/entities/property.yml"
  - "src/entities/query.yml"
  - "src/entities/relationship.yml"
  - "src/entities/value_domain.yml"
  - "src/value_domain_types/basic_type.yml"
  - "src/value_domain_types/identifier.yml"
  - "src/value_domain_types/namespace.yml"
